name: MyRestrictions

options:
  minimumXcodeGenVersion: 2.38.0
  xcodeVersion: 15.1
  deploymentTarget:
    iOS: 16.0
  groupSortPosition: top
    
targets:
  MyRestrictions:
    type: application
    platform: iOS
    deploymentTarget: 16.0
    settings:
      base:
        INFOPLIST_FILE: MyRestrictions/Info.plist
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        TARGETED_DEVICE_FAMILY: 1 # supports iPhone(1)
        PRODUCT_BUNDLE_PACKAGE_TYPE: 'APPL'
        PRODUCT_BUNDLE_IDENTIFIER: 'com.andrewfirsenko.myrestrictions'
        PRODUCT_BUNDLE_NAME: 'Template App'
        ENABLE_USER_SCRIPT_SANDBOXING: false
    sources:
      - path: MyRestrictions
    preBuildScripts:
      - path: scripts/swiftgen.sh
        name: SwiftGen
        outputFiles:
          - $(DERIVED_FILE_DIR)/output
